token: 7169955608:AAEVN9pW0Ct-nmehweXvCuNEy2DZXmsfNg8

#seconds
max_download_time: 30

#minutes
max_video_duration: 60

#tgbotapi logger
debug: false

#custom logger
logging: true

bot_username: noti_trade_bot